# Persoonlijke variabeleen 
dbt_output_path: C:\Users\Max\Github\proigia_dbt\models\dm_dash_new # Pad waar de gegenereerde dbt modellen worden opgeslagen
dbt_macro_path: C:\Users\Max\Github\proigia_dbt\macros\dm_dash_new # Pad waar de dbt macro's worden opgeslagen
proigia_defintion_path: C:\Users\Max\Github\proigia_definition # Pad naar de proigia definitie bestanden

# Logging level: 'all' (INFO+), 'error' (ERROR only), 'debug' (DEBUG+), 'warning' (WARNING+)
# Het selecteren van een log level niveau heeft invloed op de hoeveelheid informatie die wordt gelogd tijdens de uitvoering van het script.
log_level: info

# Operationele variabelen voornamelijk voor het genereren van de modellen
ignored_keywords:
  - aggregate
  - column_properties

# Function to macro mappings: SQL functions that should be replaced with dbt macros
# Format: function_name (case-insensitive)
functions:
  - clean_icpc
  - get_number
  - hvz_risico_rh24
  - qrisk3_male
  - qrisk3_female

table_functions:
  - override_kwartaal
  - patient_kwartaal
  - get_hist_kwartaalindicatoren

macros:
  - translate_labcode_answers

# Table macros: macros that return table results, wrapped in TABLE(...)
table_macros: []
# These are typically materialized views or other dbt models that need to be referenced
model_refs:
  - proigia_labcodes

# Table mapping: Specific table references that should be mapped to different schemas/tables
# Format: "source_schema.source_table": "target_schema.target_table"
# Supports {{agb}} placeholder in target
table_mapping:
  public.medewerker: "{{ source('DWH', 'medewerker_manual') }}"
  public.patient_hashes: "{{ source('DWH', 'intercity_delivery') }}"
  public.refuse: "{{ source('DWH', 'refuse') }}"
  public.get_hist_kwartaalindicatoren(CURRENT_DATE, 'kwartaal_ind_dm_pop_v3_0_indicatoren_tb' , 9): "{{ref('kwartaal_indicatoren')}}"
  public.key_value_store: "{{ source('DWH_2', 'key_value_store') }}"

# List of report folders that should be materialized as materialized_view in dbt
materialized_view_reports:
  - proigia_zorggroep_criteria_v4_0
  - proigia_basisrapportage

skip_files:
- osteoporose_53530008_ind.pry

skip_folders:
#- proigia_zg_criteria_v3

default_zg_agb: 53530000