# Persoonlijke variabeleen 
dbt_output_path: C:\Users\Max\Github\proigia_dbt\models\dm_dash_new # Pad waar de gegenereerde dbt modellen worden opgeslagen
dbt_macro_path: C:\Users\Max\Github\proigia_dbt\macros\dm_dash_new # Pad waar de dbt macro's worden opgeslagen
proigia_defintion_path: C:\Users\Max\Github\proigia_definition # Pad naar de proigia definitie bestanden

# Logging level: 'all' (INFO+), 'error' (ERROR only), 'debug' (DEBUG+), 'warning' (WARNING+)
# Het selecteren van een log level niveau heeft invloed op de hoeveelheid informatie die wordt gelogd tijdens de uitvoering van het script.
log_level: debug

# Operationele variabelen voornamelijk voor het genereren van de modellen
ignored_keywords:
  - aggregate
  - column_properties

seed_tabellen:
  nhg_labcodes: dwh.{{praktijk_agb}}.nhg_labcodes

# Function to macro mappings: SQL functions that should be replaced with dbt macros
# Format: function_name (case-insensitive)
function_macros:
  - clean_icpc
